#2.配置相关信息
server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: Xh710708

  boot:
    admin:
      client:
        url: http://localhost:8080

management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

info:
  appName: @project.artifactId@
  version: @project.version@
  company: 传智教育
  author: itheima

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

